/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPharmarcistRecordsRouteImport } from './routes/dashboard/pharmarcist/records'
import { Route as DashboardPharmarcistPrescriptionsRouteImport } from './routes/dashboard/pharmarcist/prescriptions'
import { Route as DashboardPharmarcistPharmacy_ordersRouteImport } from './routes/dashboard/pharmarcist/pharmacy_orders'
import { Route as DashboardPharmarcistPaymentsRouteImport } from './routes/dashboard/pharmarcist/payments'
import { Route as DashboardPharmarcistPatientsRouteImport } from './routes/dashboard/pharmarcist/patients'
import { Route as DashboardPatientsMedicinesRouteImport } from './routes/dashboard/patients/medicines'
import { Route as DashboardPatientsDoctorsRouteImport } from './routes/dashboard/patients/doctors'
import { Route as DashboardPatientsAppointmentsRouteImport } from './routes/dashboard/patients/appointments'
import { Route as DashboardDoctorsPrescriptionsRouteImport } from './routes/dashboard/doctors/prescriptions'
import { Route as DashboardDoctorsPatientsRouteImport } from './routes/dashboard/doctors/patients'
import { Route as DashboardDoctorsAppointmentsRouteImport } from './routes/dashboard/doctors/appointments'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminRecordsRouteImport } from './routes/dashboard/admin/records'
import { Route as DashboardAdminPrescriptionsRouteImport } from './routes/dashboard/admin/prescriptions'
import { Route as DashboardAdminPharmacy_ordersRouteImport } from './routes/dashboard/admin/pharmacy_orders'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard/admin/payments'
import { Route as DashboardAdminPatientsRouteImport } from './routes/dashboard/admin/patients'
import { Route as DashboardAdminMedicinesRouteImport } from './routes/dashboard/admin/medicines'
import { Route as DashboardAdminDoctorsRouteImport } from './routes/dashboard/admin/doctors'
import { Route as DashboardAdminDashboardRouteImport } from './routes/dashboard/admin/dashboard'
import { Route as DashboardAdminAppointmentsRouteImport } from './routes/dashboard/admin/appointments'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPharmarcistRecordsRoute =
  DashboardPharmarcistRecordsRouteImport.update({
    id: '/pharmarcist/records',
    path: '/pharmarcist/records',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPrescriptionsRoute =
  DashboardPharmarcistPrescriptionsRouteImport.update({
    id: '/pharmarcist/prescriptions',
    path: '/pharmarcist/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPharmacy_ordersRoute =
  DashboardPharmarcistPharmacy_ordersRouteImport.update({
    id: '/pharmarcist/pharmacy_orders',
    path: '/pharmarcist/pharmacy_orders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPaymentsRoute =
  DashboardPharmarcistPaymentsRouteImport.update({
    id: '/pharmarcist/payments',
    path: '/pharmarcist/payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPatientsRoute =
  DashboardPharmarcistPatientsRouteImport.update({
    id: '/pharmarcist/patients',
    path: '/pharmarcist/patients',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsMedicinesRoute =
  DashboardPatientsMedicinesRouteImport.update({
    id: '/patients/medicines',
    path: '/patients/medicines',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsDoctorsRoute =
  DashboardPatientsDoctorsRouteImport.update({
    id: '/patients/doctors',
    path: '/patients/doctors',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsAppointmentsRoute =
  DashboardPatientsAppointmentsRouteImport.update({
    id: '/patients/appointments',
    path: '/patients/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorsPrescriptionsRoute =
  DashboardDoctorsPrescriptionsRouteImport.update({
    id: '/doctors/prescriptions',
    path: '/doctors/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorsPatientsRoute =
  DashboardDoctorsPatientsRouteImport.update({
    id: '/doctors/patients',
    path: '/doctors/patients',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorsAppointmentsRoute =
  DashboardDoctorsAppointmentsRouteImport.update({
    id: '/doctors/appointments',
    path: '/doctors/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRecordsRoute = DashboardAdminRecordsRouteImport.update({
  id: '/admin/records',
  path: '/admin/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPrescriptionsRoute =
  DashboardAdminPrescriptionsRouteImport.update({
    id: '/admin/prescriptions',
    path: '/admin/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPharmacy_ordersRoute =
  DashboardAdminPharmacy_ordersRouteImport.update({
    id: '/admin/pharmacy_orders',
    path: '/admin/pharmacy_orders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPatientsRoute = DashboardAdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMedicinesRoute = DashboardAdminMedicinesRouteImport.update({
  id: '/admin/medicines',
  path: '/admin/medicines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDoctorsRoute = DashboardAdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDashboardRoute = DashboardAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAppointmentsRoute =
  DashboardAdminAppointmentsRouteImport.update({
    id: '/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/dashboard/admin/appointments': typeof DashboardAdminAppointmentsRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/dashboard/admin/doctors': typeof DashboardAdminDoctorsRoute
  '/dashboard/admin/medicines': typeof DashboardAdminMedicinesRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/pharmacy_orders': typeof DashboardAdminPharmacy_ordersRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/admin/records': typeof DashboardAdminRecordsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctors/appointments': typeof DashboardDoctorsAppointmentsRoute
  '/dashboard/doctors/patients': typeof DashboardDoctorsPatientsRoute
  '/dashboard/doctors/prescriptions': typeof DashboardDoctorsPrescriptionsRoute
  '/dashboard/patients/appointments': typeof DashboardPatientsAppointmentsRoute
  '/dashboard/patients/doctors': typeof DashboardPatientsDoctorsRoute
  '/dashboard/patients/medicines': typeof DashboardPatientsMedicinesRoute
  '/dashboard/pharmarcist/patients': typeof DashboardPharmarcistPatientsRoute
  '/dashboard/pharmarcist/payments': typeof DashboardPharmarcistPaymentsRoute
  '/dashboard/pharmarcist/pharmacy_orders': typeof DashboardPharmarcistPharmacy_ordersRoute
  '/dashboard/pharmarcist/prescriptions': typeof DashboardPharmarcistPrescriptionsRoute
  '/dashboard/pharmarcist/records': typeof DashboardPharmarcistRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/dashboard/admin/appointments': typeof DashboardAdminAppointmentsRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/dashboard/admin/doctors': typeof DashboardAdminDoctorsRoute
  '/dashboard/admin/medicines': typeof DashboardAdminMedicinesRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/pharmacy_orders': typeof DashboardAdminPharmacy_ordersRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/admin/records': typeof DashboardAdminRecordsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctors/appointments': typeof DashboardDoctorsAppointmentsRoute
  '/dashboard/doctors/patients': typeof DashboardDoctorsPatientsRoute
  '/dashboard/doctors/prescriptions': typeof DashboardDoctorsPrescriptionsRoute
  '/dashboard/patients/appointments': typeof DashboardPatientsAppointmentsRoute
  '/dashboard/patients/doctors': typeof DashboardPatientsDoctorsRoute
  '/dashboard/patients/medicines': typeof DashboardPatientsMedicinesRoute
  '/dashboard/pharmarcist/patients': typeof DashboardPharmarcistPatientsRoute
  '/dashboard/pharmarcist/payments': typeof DashboardPharmarcistPaymentsRoute
  '/dashboard/pharmarcist/pharmacy_orders': typeof DashboardPharmarcistPharmacy_ordersRoute
  '/dashboard/pharmarcist/prescriptions': typeof DashboardPharmarcistPrescriptionsRoute
  '/dashboard/pharmarcist/records': typeof DashboardPharmarcistRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/dashboard/admin/appointments': typeof DashboardAdminAppointmentsRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/dashboard/admin/doctors': typeof DashboardAdminDoctorsRoute
  '/dashboard/admin/medicines': typeof DashboardAdminMedicinesRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/pharmacy_orders': typeof DashboardAdminPharmacy_ordersRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/admin/records': typeof DashboardAdminRecordsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctors/appointments': typeof DashboardDoctorsAppointmentsRoute
  '/dashboard/doctors/patients': typeof DashboardDoctorsPatientsRoute
  '/dashboard/doctors/prescriptions': typeof DashboardDoctorsPrescriptionsRoute
  '/dashboard/patients/appointments': typeof DashboardPatientsAppointmentsRoute
  '/dashboard/patients/doctors': typeof DashboardPatientsDoctorsRoute
  '/dashboard/patients/medicines': typeof DashboardPatientsMedicinesRoute
  '/dashboard/pharmarcist/patients': typeof DashboardPharmarcistPatientsRoute
  '/dashboard/pharmarcist/payments': typeof DashboardPharmarcistPaymentsRoute
  '/dashboard/pharmarcist/pharmacy_orders': typeof DashboardPharmarcistPharmacy_ordersRoute
  '/dashboard/pharmarcist/prescriptions': typeof DashboardPharmarcistPrescriptionsRoute
  '/dashboard/pharmarcist/records': typeof DashboardPharmarcistRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/registration'
    | '/dashboard/admin/appointments'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/doctors'
    | '/dashboard/admin/medicines'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pharmacy_orders'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/admin/records'
    | '/dashboard/admin/users'
    | '/dashboard/doctors/appointments'
    | '/dashboard/doctors/patients'
    | '/dashboard/doctors/prescriptions'
    | '/dashboard/patients/appointments'
    | '/dashboard/patients/doctors'
    | '/dashboard/patients/medicines'
    | '/dashboard/pharmarcist/patients'
    | '/dashboard/pharmarcist/payments'
    | '/dashboard/pharmarcist/pharmacy_orders'
    | '/dashboard/pharmarcist/prescriptions'
    | '/dashboard/pharmarcist/records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/registration'
    | '/dashboard/admin/appointments'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/doctors'
    | '/dashboard/admin/medicines'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pharmacy_orders'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/admin/records'
    | '/dashboard/admin/users'
    | '/dashboard/doctors/appointments'
    | '/dashboard/doctors/patients'
    | '/dashboard/doctors/prescriptions'
    | '/dashboard/patients/appointments'
    | '/dashboard/patients/doctors'
    | '/dashboard/patients/medicines'
    | '/dashboard/pharmarcist/patients'
    | '/dashboard/pharmarcist/payments'
    | '/dashboard/pharmarcist/pharmacy_orders'
    | '/dashboard/pharmarcist/prescriptions'
    | '/dashboard/pharmarcist/records'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/registration'
    | '/dashboard/admin/appointments'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/doctors'
    | '/dashboard/admin/medicines'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pharmacy_orders'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/admin/records'
    | '/dashboard/admin/users'
    | '/dashboard/doctors/appointments'
    | '/dashboard/doctors/patients'
    | '/dashboard/doctors/prescriptions'
    | '/dashboard/patients/appointments'
    | '/dashboard/patients/doctors'
    | '/dashboard/patients/medicines'
    | '/dashboard/pharmarcist/patients'
    | '/dashboard/pharmarcist/payments'
    | '/dashboard/pharmarcist/pharmacy_orders'
    | '/dashboard/pharmarcist/prescriptions'
    | '/dashboard/pharmarcist/records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pharmarcist/records': {
      id: '/dashboard/pharmarcist/records'
      path: '/pharmarcist/records'
      fullPath: '/dashboard/pharmarcist/records'
      preLoaderRoute: typeof DashboardPharmarcistRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/prescriptions': {
      id: '/dashboard/pharmarcist/prescriptions'
      path: '/pharmarcist/prescriptions'
      fullPath: '/dashboard/pharmarcist/prescriptions'
      preLoaderRoute: typeof DashboardPharmarcistPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/pharmacy_orders': {
      id: '/dashboard/pharmarcist/pharmacy_orders'
      path: '/pharmarcist/pharmacy_orders'
      fullPath: '/dashboard/pharmarcist/pharmacy_orders'
      preLoaderRoute: typeof DashboardPharmarcistPharmacy_ordersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/payments': {
      id: '/dashboard/pharmarcist/payments'
      path: '/pharmarcist/payments'
      fullPath: '/dashboard/pharmarcist/payments'
      preLoaderRoute: typeof DashboardPharmarcistPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/patients': {
      id: '/dashboard/pharmarcist/patients'
      path: '/pharmarcist/patients'
      fullPath: '/dashboard/pharmarcist/patients'
      preLoaderRoute: typeof DashboardPharmarcistPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/medicines': {
      id: '/dashboard/patients/medicines'
      path: '/patients/medicines'
      fullPath: '/dashboard/patients/medicines'
      preLoaderRoute: typeof DashboardPatientsMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/doctors': {
      id: '/dashboard/patients/doctors'
      path: '/patients/doctors'
      fullPath: '/dashboard/patients/doctors'
      preLoaderRoute: typeof DashboardPatientsDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients/appointments': {
      id: '/dashboard/patients/appointments'
      path: '/patients/appointments'
      fullPath: '/dashboard/patients/appointments'
      preLoaderRoute: typeof DashboardPatientsAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors/prescriptions': {
      id: '/dashboard/doctors/prescriptions'
      path: '/doctors/prescriptions'
      fullPath: '/dashboard/doctors/prescriptions'
      preLoaderRoute: typeof DashboardDoctorsPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors/patients': {
      id: '/dashboard/doctors/patients'
      path: '/doctors/patients'
      fullPath: '/dashboard/doctors/patients'
      preLoaderRoute: typeof DashboardDoctorsPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctors/appointments': {
      id: '/dashboard/doctors/appointments'
      path: '/doctors/appointments'
      fullPath: '/dashboard/doctors/appointments'
      preLoaderRoute: typeof DashboardDoctorsAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/records': {
      id: '/dashboard/admin/records'
      path: '/admin/records'
      fullPath: '/dashboard/admin/records'
      preLoaderRoute: typeof DashboardAdminRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/prescriptions': {
      id: '/dashboard/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/dashboard/admin/prescriptions'
      preLoaderRoute: typeof DashboardAdminPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/pharmacy_orders': {
      id: '/dashboard/admin/pharmacy_orders'
      path: '/admin/pharmacy_orders'
      fullPath: '/dashboard/admin/pharmacy_orders'
      preLoaderRoute: typeof DashboardAdminPharmacy_ordersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/patients': {
      id: '/dashboard/admin/patients'
      path: '/admin/patients'
      fullPath: '/dashboard/admin/patients'
      preLoaderRoute: typeof DashboardAdminPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/medicines': {
      id: '/dashboard/admin/medicines'
      path: '/admin/medicines'
      fullPath: '/dashboard/admin/medicines'
      preLoaderRoute: typeof DashboardAdminMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/doctors': {
      id: '/dashboard/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/dashboard/admin/doctors'
      preLoaderRoute: typeof DashboardAdminDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/dashboard': {
      id: '/dashboard/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/dashboard/admin/dashboard'
      preLoaderRoute: typeof DashboardAdminDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/appointments': {
      id: '/dashboard/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/dashboard/admin/appointments'
      preLoaderRoute: typeof DashboardAdminAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminAppointmentsRoute: typeof DashboardAdminAppointmentsRoute
  DashboardAdminDashboardRoute: typeof DashboardAdminDashboardRoute
  DashboardAdminDoctorsRoute: typeof DashboardAdminDoctorsRoute
  DashboardAdminMedicinesRoute: typeof DashboardAdminMedicinesRoute
  DashboardAdminPatientsRoute: typeof DashboardAdminPatientsRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminPharmacy_ordersRoute: typeof DashboardAdminPharmacy_ordersRoute
  DashboardAdminPrescriptionsRoute: typeof DashboardAdminPrescriptionsRoute
  DashboardAdminRecordsRoute: typeof DashboardAdminRecordsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardDoctorsAppointmentsRoute: typeof DashboardDoctorsAppointmentsRoute
  DashboardDoctorsPatientsRoute: typeof DashboardDoctorsPatientsRoute
  DashboardDoctorsPrescriptionsRoute: typeof DashboardDoctorsPrescriptionsRoute
  DashboardPatientsAppointmentsRoute: typeof DashboardPatientsAppointmentsRoute
  DashboardPatientsDoctorsRoute: typeof DashboardPatientsDoctorsRoute
  DashboardPatientsMedicinesRoute: typeof DashboardPatientsMedicinesRoute
  DashboardPharmarcistPatientsRoute: typeof DashboardPharmarcistPatientsRoute
  DashboardPharmarcistPaymentsRoute: typeof DashboardPharmarcistPaymentsRoute
  DashboardPharmarcistPharmacy_ordersRoute: typeof DashboardPharmarcistPharmacy_ordersRoute
  DashboardPharmarcistPrescriptionsRoute: typeof DashboardPharmarcistPrescriptionsRoute
  DashboardPharmarcistRecordsRoute: typeof DashboardPharmarcistRecordsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminAppointmentsRoute: DashboardAdminAppointmentsRoute,
  DashboardAdminDashboardRoute: DashboardAdminDashboardRoute,
  DashboardAdminDoctorsRoute: DashboardAdminDoctorsRoute,
  DashboardAdminMedicinesRoute: DashboardAdminMedicinesRoute,
  DashboardAdminPatientsRoute: DashboardAdminPatientsRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminPharmacy_ordersRoute: DashboardAdminPharmacy_ordersRoute,
  DashboardAdminPrescriptionsRoute: DashboardAdminPrescriptionsRoute,
  DashboardAdminRecordsRoute: DashboardAdminRecordsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardDoctorsAppointmentsRoute: DashboardDoctorsAppointmentsRoute,
  DashboardDoctorsPatientsRoute: DashboardDoctorsPatientsRoute,
  DashboardDoctorsPrescriptionsRoute: DashboardDoctorsPrescriptionsRoute,
  DashboardPatientsAppointmentsRoute: DashboardPatientsAppointmentsRoute,
  DashboardPatientsDoctorsRoute: DashboardPatientsDoctorsRoute,
  DashboardPatientsMedicinesRoute: DashboardPatientsMedicinesRoute,
  DashboardPharmarcistPatientsRoute: DashboardPharmarcistPatientsRoute,
  DashboardPharmarcistPaymentsRoute: DashboardPharmarcistPaymentsRoute,
  DashboardPharmarcistPharmacy_ordersRoute:
    DashboardPharmarcistPharmacy_ordersRoute,
  DashboardPharmarcistPrescriptionsRoute:
    DashboardPharmarcistPrescriptionsRoute,
  DashboardPharmarcistRecordsRoute: DashboardPharmarcistRecordsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
