/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPharmarcistRecordsRouteImport } from './routes/dashboard/pharmarcist/records'
import { Route as DashboardPharmarcistPrescriptionsRouteImport } from './routes/dashboard/pharmarcist/prescriptions'
import { Route as DashboardPharmarcistPharmacy_ordersRouteImport } from './routes/dashboard/pharmarcist/pharmacy_orders'
import { Route as DashboardPharmarcistPaymentsRouteImport } from './routes/dashboard/pharmarcist/payments'
import { Route as DashboardPharmarcistPatientsRouteImport } from './routes/dashboard/pharmarcist/patients'
import { Route as DashboardPatientMedicinesRouteImport } from './routes/dashboard/patient/medicines'
import { Route as DashboardPatientDoctorsRouteImport } from './routes/dashboard/patient/doctors'
import { Route as DashboardPatientAppointmentsRouteImport } from './routes/dashboard/patient/appointments'
import { Route as DashboardDoctorRecordsRouteImport } from './routes/dashboard/doctor/records'
import { Route as DashboardDoctorPrescriptionsRouteImport } from './routes/dashboard/doctor/prescriptions'
import { Route as DashboardDoctorAppointmentsRouteImport } from './routes/dashboard/doctor/appointments'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminRecordsRouteImport } from './routes/dashboard/admin/records'
import { Route as DashboardAdminPrescriptionsRouteImport } from './routes/dashboard/admin/prescriptions'
import { Route as DashboardAdminPharmacy_ordersRouteImport } from './routes/dashboard/admin/pharmacy_orders'
import { Route as DashboardAdminPaymentsRouteImport } from './routes/dashboard/admin/payments'
import { Route as DashboardAdminPatientsRouteImport } from './routes/dashboard/admin/patients'
import { Route as DashboardAdminMedicinesRouteImport } from './routes/dashboard/admin/medicines'
import { Route as DashboardAdminDoctorsRouteImport } from './routes/dashboard/admin/doctors'
import { Route as DashboardAdminDashboardRouteImport } from './routes/dashboard/admin/dashboard'
import { Route as DashboardAdminAppointmentsRouteImport } from './routes/dashboard/admin/appointments'
import { Route as DashboardDoctorPatientIndexRouteImport } from './routes/dashboard/doctor/patient/index'
import { Route as DashboardDoctorPatientPatientIdRouteImport } from './routes/dashboard/doctor/patient/$patientId'

const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPharmarcistRecordsRoute =
  DashboardPharmarcistRecordsRouteImport.update({
    id: '/pharmarcist/records',
    path: '/pharmarcist/records',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPrescriptionsRoute =
  DashboardPharmarcistPrescriptionsRouteImport.update({
    id: '/pharmarcist/prescriptions',
    path: '/pharmarcist/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPharmacy_ordersRoute =
  DashboardPharmarcistPharmacy_ordersRouteImport.update({
    id: '/pharmarcist/pharmacy_orders',
    path: '/pharmarcist/pharmacy_orders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPaymentsRoute =
  DashboardPharmarcistPaymentsRouteImport.update({
    id: '/pharmarcist/payments',
    path: '/pharmarcist/payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPharmarcistPatientsRoute =
  DashboardPharmarcistPatientsRouteImport.update({
    id: '/pharmarcist/patients',
    path: '/pharmarcist/patients',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientMedicinesRoute =
  DashboardPatientMedicinesRouteImport.update({
    id: '/patient/medicines',
    path: '/patient/medicines',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientDoctorsRoute = DashboardPatientDoctorsRouteImport.update({
  id: '/patient/doctors',
  path: '/patient/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientAppointmentsRoute =
  DashboardPatientAppointmentsRouteImport.update({
    id: '/patient/appointments',
    path: '/patient/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorRecordsRoute = DashboardDoctorRecordsRouteImport.update({
  id: '/doctor/records',
  path: '/doctor/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorPrescriptionsRoute =
  DashboardDoctorPrescriptionsRouteImport.update({
    id: '/doctor/prescriptions',
    path: '/doctor/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorAppointmentsRoute =
  DashboardDoctorAppointmentsRouteImport.update({
    id: '/doctor/appointments',
    path: '/doctor/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRecordsRoute = DashboardAdminRecordsRouteImport.update({
  id: '/admin/records',
  path: '/admin/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPrescriptionsRoute =
  DashboardAdminPrescriptionsRouteImport.update({
    id: '/admin/prescriptions',
    path: '/admin/prescriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPharmacy_ordersRoute =
  DashboardAdminPharmacy_ordersRouteImport.update({
    id: '/admin/pharmacy_orders',
    path: '/admin/pharmacy_orders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminPaymentsRoute = DashboardAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminPatientsRoute = DashboardAdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminMedicinesRoute = DashboardAdminMedicinesRouteImport.update({
  id: '/admin/medicines',
  path: '/admin/medicines',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDoctorsRoute = DashboardAdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminDashboardRoute = DashboardAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAppointmentsRoute =
  DashboardAdminAppointmentsRouteImport.update({
    id: '/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorPatientIndexRoute =
  DashboardDoctorPatientIndexRouteImport.update({
    id: '/doctor/patient/',
    path: '/doctor/patient/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorPatientPatientIdRoute =
  DashboardDoctorPatientPatientIdRouteImport.update({
    id: '/doctor/patient/$patientId',
    path: '/doctor/patient/$patientId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/dashboard/admin/appointments': typeof DashboardAdminAppointmentsRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/dashboard/admin/doctors': typeof DashboardAdminDoctorsRoute
  '/dashboard/admin/medicines': typeof DashboardAdminMedicinesRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/pharmacy_orders': typeof DashboardAdminPharmacy_ordersRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/admin/records': typeof DashboardAdminRecordsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/records': typeof DashboardDoctorRecordsRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/doctors': typeof DashboardPatientDoctorsRoute
  '/dashboard/patient/medicines': typeof DashboardPatientMedicinesRoute
  '/dashboard/pharmarcist/patients': typeof DashboardPharmarcistPatientsRoute
  '/dashboard/pharmarcist/payments': typeof DashboardPharmarcistPaymentsRoute
  '/dashboard/pharmarcist/pharmacy_orders': typeof DashboardPharmarcistPharmacy_ordersRoute
  '/dashboard/pharmarcist/prescriptions': typeof DashboardPharmarcistPrescriptionsRoute
  '/dashboard/pharmarcist/records': typeof DashboardPharmarcistRecordsRoute
  '/dashboard/doctor/patient/$patientId': typeof DashboardDoctorPatientPatientIdRoute
  '/dashboard/doctor/patient': typeof DashboardDoctorPatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/dashboard/admin/appointments': typeof DashboardAdminAppointmentsRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/dashboard/admin/doctors': typeof DashboardAdminDoctorsRoute
  '/dashboard/admin/medicines': typeof DashboardAdminMedicinesRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/pharmacy_orders': typeof DashboardAdminPharmacy_ordersRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/admin/records': typeof DashboardAdminRecordsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/records': typeof DashboardDoctorRecordsRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/doctors': typeof DashboardPatientDoctorsRoute
  '/dashboard/patient/medicines': typeof DashboardPatientMedicinesRoute
  '/dashboard/pharmarcist/patients': typeof DashboardPharmarcistPatientsRoute
  '/dashboard/pharmarcist/payments': typeof DashboardPharmarcistPaymentsRoute
  '/dashboard/pharmarcist/pharmacy_orders': typeof DashboardPharmarcistPharmacy_ordersRoute
  '/dashboard/pharmarcist/prescriptions': typeof DashboardPharmarcistPrescriptionsRoute
  '/dashboard/pharmarcist/records': typeof DashboardPharmarcistRecordsRoute
  '/dashboard/doctor/patient/$patientId': typeof DashboardDoctorPatientPatientIdRoute
  '/dashboard/doctor/patient': typeof DashboardDoctorPatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/dashboard/admin/appointments': typeof DashboardAdminAppointmentsRoute
  '/dashboard/admin/dashboard': typeof DashboardAdminDashboardRoute
  '/dashboard/admin/doctors': typeof DashboardAdminDoctorsRoute
  '/dashboard/admin/medicines': typeof DashboardAdminMedicinesRoute
  '/dashboard/admin/patients': typeof DashboardAdminPatientsRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsRoute
  '/dashboard/admin/pharmacy_orders': typeof DashboardAdminPharmacy_ordersRoute
  '/dashboard/admin/prescriptions': typeof DashboardAdminPrescriptionsRoute
  '/dashboard/admin/records': typeof DashboardAdminRecordsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/doctor/appointments': typeof DashboardDoctorAppointmentsRoute
  '/dashboard/doctor/prescriptions': typeof DashboardDoctorPrescriptionsRoute
  '/dashboard/doctor/records': typeof DashboardDoctorRecordsRoute
  '/dashboard/patient/appointments': typeof DashboardPatientAppointmentsRoute
  '/dashboard/patient/doctors': typeof DashboardPatientDoctorsRoute
  '/dashboard/patient/medicines': typeof DashboardPatientMedicinesRoute
  '/dashboard/pharmarcist/patients': typeof DashboardPharmarcistPatientsRoute
  '/dashboard/pharmarcist/payments': typeof DashboardPharmarcistPaymentsRoute
  '/dashboard/pharmarcist/pharmacy_orders': typeof DashboardPharmarcistPharmacy_ordersRoute
  '/dashboard/pharmarcist/prescriptions': typeof DashboardPharmarcistPrescriptionsRoute
  '/dashboard/pharmarcist/records': typeof DashboardPharmarcistRecordsRoute
  '/dashboard/doctor/patient/$patientId': typeof DashboardDoctorPatientPatientIdRoute
  '/dashboard/doctor/patient/': typeof DashboardDoctorPatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/registration'
    | '/dashboard/admin/appointments'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/doctors'
    | '/dashboard/admin/medicines'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pharmacy_orders'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/admin/records'
    | '/dashboard/admin/users'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/records'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/doctors'
    | '/dashboard/patient/medicines'
    | '/dashboard/pharmarcist/patients'
    | '/dashboard/pharmarcist/payments'
    | '/dashboard/pharmarcist/pharmacy_orders'
    | '/dashboard/pharmarcist/prescriptions'
    | '/dashboard/pharmarcist/records'
    | '/dashboard/doctor/patient/$patientId'
    | '/dashboard/doctor/patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/registration'
    | '/dashboard/admin/appointments'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/doctors'
    | '/dashboard/admin/medicines'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pharmacy_orders'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/admin/records'
    | '/dashboard/admin/users'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/records'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/doctors'
    | '/dashboard/patient/medicines'
    | '/dashboard/pharmarcist/patients'
    | '/dashboard/pharmarcist/payments'
    | '/dashboard/pharmarcist/pharmacy_orders'
    | '/dashboard/pharmarcist/prescriptions'
    | '/dashboard/pharmarcist/records'
    | '/dashboard/doctor/patient/$patientId'
    | '/dashboard/doctor/patient'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/registration'
    | '/dashboard/admin/appointments'
    | '/dashboard/admin/dashboard'
    | '/dashboard/admin/doctors'
    | '/dashboard/admin/medicines'
    | '/dashboard/admin/patients'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pharmacy_orders'
    | '/dashboard/admin/prescriptions'
    | '/dashboard/admin/records'
    | '/dashboard/admin/users'
    | '/dashboard/doctor/appointments'
    | '/dashboard/doctor/prescriptions'
    | '/dashboard/doctor/records'
    | '/dashboard/patient/appointments'
    | '/dashboard/patient/doctors'
    | '/dashboard/patient/medicines'
    | '/dashboard/pharmarcist/patients'
    | '/dashboard/pharmarcist/payments'
    | '/dashboard/pharmarcist/pharmacy_orders'
    | '/dashboard/pharmarcist/prescriptions'
    | '/dashboard/pharmarcist/records'
    | '/dashboard/doctor/patient/$patientId'
    | '/dashboard/doctor/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pharmarcist/records': {
      id: '/dashboard/pharmarcist/records'
      path: '/pharmarcist/records'
      fullPath: '/dashboard/pharmarcist/records'
      preLoaderRoute: typeof DashboardPharmarcistRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/prescriptions': {
      id: '/dashboard/pharmarcist/prescriptions'
      path: '/pharmarcist/prescriptions'
      fullPath: '/dashboard/pharmarcist/prescriptions'
      preLoaderRoute: typeof DashboardPharmarcistPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/pharmacy_orders': {
      id: '/dashboard/pharmarcist/pharmacy_orders'
      path: '/pharmarcist/pharmacy_orders'
      fullPath: '/dashboard/pharmarcist/pharmacy_orders'
      preLoaderRoute: typeof DashboardPharmarcistPharmacy_ordersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/payments': {
      id: '/dashboard/pharmarcist/payments'
      path: '/pharmarcist/payments'
      fullPath: '/dashboard/pharmarcist/payments'
      preLoaderRoute: typeof DashboardPharmarcistPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmarcist/patients': {
      id: '/dashboard/pharmarcist/patients'
      path: '/pharmarcist/patients'
      fullPath: '/dashboard/pharmarcist/patients'
      preLoaderRoute: typeof DashboardPharmarcistPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/medicines': {
      id: '/dashboard/patient/medicines'
      path: '/patient/medicines'
      fullPath: '/dashboard/patient/medicines'
      preLoaderRoute: typeof DashboardPatientMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/doctors': {
      id: '/dashboard/patient/doctors'
      path: '/patient/doctors'
      fullPath: '/dashboard/patient/doctors'
      preLoaderRoute: typeof DashboardPatientDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patient/appointments': {
      id: '/dashboard/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/dashboard/patient/appointments'
      preLoaderRoute: typeof DashboardPatientAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/records': {
      id: '/dashboard/doctor/records'
      path: '/doctor/records'
      fullPath: '/dashboard/doctor/records'
      preLoaderRoute: typeof DashboardDoctorRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/prescriptions': {
      id: '/dashboard/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/dashboard/doctor/prescriptions'
      preLoaderRoute: typeof DashboardDoctorPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/appointments': {
      id: '/dashboard/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/dashboard/doctor/appointments'
      preLoaderRoute: typeof DashboardDoctorAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/records': {
      id: '/dashboard/admin/records'
      path: '/admin/records'
      fullPath: '/dashboard/admin/records'
      preLoaderRoute: typeof DashboardAdminRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/prescriptions': {
      id: '/dashboard/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/dashboard/admin/prescriptions'
      preLoaderRoute: typeof DashboardAdminPrescriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/pharmacy_orders': {
      id: '/dashboard/admin/pharmacy_orders'
      path: '/admin/pharmacy_orders'
      fullPath: '/dashboard/admin/pharmacy_orders'
      preLoaderRoute: typeof DashboardAdminPharmacy_ordersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/payments': {
      id: '/dashboard/admin/payments'
      path: '/admin/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/patients': {
      id: '/dashboard/admin/patients'
      path: '/admin/patients'
      fullPath: '/dashboard/admin/patients'
      preLoaderRoute: typeof DashboardAdminPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/medicines': {
      id: '/dashboard/admin/medicines'
      path: '/admin/medicines'
      fullPath: '/dashboard/admin/medicines'
      preLoaderRoute: typeof DashboardAdminMedicinesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/doctors': {
      id: '/dashboard/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/dashboard/admin/doctors'
      preLoaderRoute: typeof DashboardAdminDoctorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/dashboard': {
      id: '/dashboard/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/dashboard/admin/dashboard'
      preLoaderRoute: typeof DashboardAdminDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/appointments': {
      id: '/dashboard/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/dashboard/admin/appointments'
      preLoaderRoute: typeof DashboardAdminAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/patient/': {
      id: '/dashboard/doctor/patient/'
      path: '/doctor/patient'
      fullPath: '/dashboard/doctor/patient'
      preLoaderRoute: typeof DashboardDoctorPatientIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doctor/patient/$patientId': {
      id: '/dashboard/doctor/patient/$patientId'
      path: '/doctor/patient/$patientId'
      fullPath: '/dashboard/doctor/patient/$patientId'
      preLoaderRoute: typeof DashboardDoctorPatientPatientIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminAppointmentsRoute: typeof DashboardAdminAppointmentsRoute
  DashboardAdminDashboardRoute: typeof DashboardAdminDashboardRoute
  DashboardAdminDoctorsRoute: typeof DashboardAdminDoctorsRoute
  DashboardAdminMedicinesRoute: typeof DashboardAdminMedicinesRoute
  DashboardAdminPatientsRoute: typeof DashboardAdminPatientsRoute
  DashboardAdminPaymentsRoute: typeof DashboardAdminPaymentsRoute
  DashboardAdminPharmacy_ordersRoute: typeof DashboardAdminPharmacy_ordersRoute
  DashboardAdminPrescriptionsRoute: typeof DashboardAdminPrescriptionsRoute
  DashboardAdminRecordsRoute: typeof DashboardAdminRecordsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardDoctorAppointmentsRoute: typeof DashboardDoctorAppointmentsRoute
  DashboardDoctorPrescriptionsRoute: typeof DashboardDoctorPrescriptionsRoute
  DashboardDoctorRecordsRoute: typeof DashboardDoctorRecordsRoute
  DashboardPatientAppointmentsRoute: typeof DashboardPatientAppointmentsRoute
  DashboardPatientDoctorsRoute: typeof DashboardPatientDoctorsRoute
  DashboardPatientMedicinesRoute: typeof DashboardPatientMedicinesRoute
  DashboardPharmarcistPatientsRoute: typeof DashboardPharmarcistPatientsRoute
  DashboardPharmarcistPaymentsRoute: typeof DashboardPharmarcistPaymentsRoute
  DashboardPharmarcistPharmacy_ordersRoute: typeof DashboardPharmarcistPharmacy_ordersRoute
  DashboardPharmarcistPrescriptionsRoute: typeof DashboardPharmarcistPrescriptionsRoute
  DashboardPharmarcistRecordsRoute: typeof DashboardPharmarcistRecordsRoute
  DashboardDoctorPatientPatientIdRoute: typeof DashboardDoctorPatientPatientIdRoute
  DashboardDoctorPatientIndexRoute: typeof DashboardDoctorPatientIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminAppointmentsRoute: DashboardAdminAppointmentsRoute,
  DashboardAdminDashboardRoute: DashboardAdminDashboardRoute,
  DashboardAdminDoctorsRoute: DashboardAdminDoctorsRoute,
  DashboardAdminMedicinesRoute: DashboardAdminMedicinesRoute,
  DashboardAdminPatientsRoute: DashboardAdminPatientsRoute,
  DashboardAdminPaymentsRoute: DashboardAdminPaymentsRoute,
  DashboardAdminPharmacy_ordersRoute: DashboardAdminPharmacy_ordersRoute,
  DashboardAdminPrescriptionsRoute: DashboardAdminPrescriptionsRoute,
  DashboardAdminRecordsRoute: DashboardAdminRecordsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardDoctorAppointmentsRoute: DashboardDoctorAppointmentsRoute,
  DashboardDoctorPrescriptionsRoute: DashboardDoctorPrescriptionsRoute,
  DashboardDoctorRecordsRoute: DashboardDoctorRecordsRoute,
  DashboardPatientAppointmentsRoute: DashboardPatientAppointmentsRoute,
  DashboardPatientDoctorsRoute: DashboardPatientDoctorsRoute,
  DashboardPatientMedicinesRoute: DashboardPatientMedicinesRoute,
  DashboardPharmarcistPatientsRoute: DashboardPharmarcistPatientsRoute,
  DashboardPharmarcistPaymentsRoute: DashboardPharmarcistPaymentsRoute,
  DashboardPharmarcistPharmacy_ordersRoute:
    DashboardPharmarcistPharmacy_ordersRoute,
  DashboardPharmarcistPrescriptionsRoute:
    DashboardPharmarcistPrescriptionsRoute,
  DashboardPharmarcistRecordsRoute: DashboardPharmarcistRecordsRoute,
  DashboardDoctorPatientPatientIdRoute: DashboardDoctorPatientPatientIdRoute,
  DashboardDoctorPatientIndexRoute: DashboardDoctorPatientIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
